### ISSUE TITLE
gender-neutral betas vs gender-specific betas

### ISSUE THREAD

**Issue by mrT23** [muelea/shapy#7]
Hi, great work.

i have a question about "gender-neutral betas" vs "gender-specific betas":

the neural network in "regressor/demo.py", that predicts the betas, doesnt have a gender_type category in its "exp_cfg" config.

but the attributes network has an option for "gender-specific" betas ("model_gender"). 

Could you elaborate on this ? can the neural network predict "gender-specific" betas ?

Thanks, 
Tal

**Comment by muelea** [comment]
Hi,

the SHAPY regressor is trained to predict gender-neutral betas. The attribute network we use during regressor training predicts gender-specific attribute ratings (this is necessary, since we use different words for male/female) from gender-neutral betas.

We don't have gender-specific versions of the SHAPY regressor. What you can do to get gender-specific SMPL-X betas from the regressor is to fit the gender-specific SMPL-X model to the gender-neutral SHPAY regressor prediction.

Hope that helps.

Best,
Lea

**Comment by mrT23** [comment]
Thanks for the detailed answer :)

Tal
